server:
  port: 8761

spring:
  application:
    name: discoveryservice
  cloud:
    config:
      uri: http://127.0.0.1
      name: seok-market


## discovery 서비스에 자기 자신은 등록하지 않기 위한 설정
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false