server:
  port: 0

spring:
  application:
    name: order-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: test1357
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    io.seok.orderservice: DEBUG # 로깅 레벨을 직접 조절하기 위해 사용
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # zipkin 서버로 어느정보 비율로 추적 데이터를 전송할건지(1.0 이면 모두 전송한다는 뜻)
  endpoint:
    web:
      exposure:
        include: health , httpexchanges , info , metrics, prometheus




