server:
  port: 8888 # 기본 8888 포트로 동작 하지만 명시적으로 표기

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/workspace/Study/msa-study-kotlin-config #window
          default-label: master #브랜치 설정
