server:
  port: 8888 # 기본 8888 포트로 동작 하지만 명시적으로 표기

encrypt:
  key-store:
#    location: file:///${user.home}/apiEncryptionKey.jks
#    location: file://${user.home}/apiEncryptionKey.jks
    location: file:/apiEncryptionKey.jks #docker 사용시 해당 프로젝트에 있는파일로 사용시
    password: test1234
    alias: apiEncryptionKey

spring:
  application:
    name: config-service
  rabbitmq:
    host: rabbitmq-stream # docker 컨테이너랑 연결시사용 (아닐때는 ip주소를 쓰면됌)
    port: 5672
    username: admin
    password: admin
#  profiles:
#    active: native #profile을 native로 설정했기에 밑에 git-uri 설정은 무시됨(만약 profile설정을 따로 안했다면 git에 정보를 디폴트로 읽게 되어있음)
  cloud:
    config:
      server:
#        native:
##          search-locations: file:///${user.home}/native-local-repo #window
#          search-locations: file://${user.home}/native-local-repo #mac
        git:
          uri: https://github.com/SeokSeokNa/spring-cloud-config
#          username: [github username] #username 과 password는 git repository가 private 일때만 사용
#          password: [github token or password]
#          uri: file:///C:/workspace/Study/msa-study-kotlin-config #window
#          default-label: master #브랜치 설정

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh